services:
  app:
    build:
      context: .
      dockerfile: Dockerfile # 追加: Dockerfileへのパス
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run dev"
  redis:
    image: "redis:alpine"
